matches:
  - trigger: "<-\t"
    replace: "←"
  - trigger: "xx\t"
    replace: "×"
  - trigger: ":-\t"
    replace: "÷"
  - trigger: "*O\t"
    replace: "⍟"
  - trigger: "OO\t"
    replace: "○"
  - trigger: "|_\t"
    replace: "⊥"
  - trigger: "TT\t"
    replace: "⊤"
  - trigger: "-|\t"
    replace: "⊣"
  - trigger: "|-\t"
    replace: "⊢"
  - trigger: "=/\t"
    replace: "≠"
  - trigger: "<_\t"
    replace: "≤"
  - trigger: ">_\t"
    replace: "≥"
  - trigger: "==\t"
    replace: "≡"
  - trigger: "_=\t"
    replace: "≡"
  - trigger: "vv\t"
    replace: "∨"
  - trigger: "^^\t"
    replace: "∧"
  - trigger: "^~\t"
    replace: "⍲"
  - trigger: "v~\t"
    replace: "⍱"
  - trigger: "^|\t"
    replace: "↑"
  - trigger: "v|\t"
    replace: "↓"
  - trigger: "cc\t"
    replace: "⊂"
  - trigger: "))\t"
    replace: "⊃"
  - trigger: "c_\t"
    replace: "⊆"
  - trigger: "A|\t"
    replace: "⍋"
  - trigger: "V|\t"
    replace: "⍒"
  - trigger: "ii\t"
    replace: "⍳"
  - trigger: "i_\t"
    replace: "⍸"
  - trigger: "ee\t"
    replace: "∊"
  - trigger: "e_\t"
    replace: "⍷"
  - trigger: "uu\t"
    replace: "∪"
  - trigger: "nn\t"
    replace: "∩"
  - trigger: "/-\t"
    replace: "⌿"
  - trigger: "\\-\t"
    replace: "⍀"
  - trigger: ",-\t"
    replace: "⍪"
  - trigger: "O-\t"
    replace: "⊖"
  - trigger: "O\\\t"
    replace: "⍉"
  - trigger: "~:\t"
    replace: "⍨"
  - trigger: "*:\t"
    replace: "⍣"
  - trigger: "oo\t"
    replace: "∘"
  - trigger: "o:\t"
    replace: "⍤"
  - trigger: "O:\t"
    replace: "⍥"
  - trigger: "[]\t"
    replace: "⎕"
  - trigger: "o_\t"
    replace: "⍎"
  - trigger: "o-\t"
    replace: "⍕"
  - trigger: "To\t"
    replace: "⍕"
  - trigger: "<>\t"
    replace: "⋄"
  - trigger: "on\t"
    replace: "⍝"
  - trigger: "ww\t"
    replace: "⍵"
  - trigger: "aa\t"
    replace: "⍺"
  - trigger: "VV\t"
    replace: "∇"
  - trigger: "--\t"
    replace: "¯"
  - trigger: "0~\t"
    replace: "⍬"
  - trigger: "[-\t"
    replace: "⌹"
  - trigger: "-\t"
    replace: "⌹"
  - trigger: "[|\t"
    replace: "⌷"
  - trigger: "|]\t"
    replace: "⌷"
  - trigger: "7=\t"
    replace: "≢"
  - trigger: "Z-\t"
    replace: "≢"
  - trigger: "77\t"
    replace: "⌈"
  - trigger: "FF\t"
    replace: "⌈"
  - trigger: "ll\t"
    replace: "⌊"
  - trigger: "LL\t"
    replace: "⌊"
  - trigger: "::\t"
    replace: "¨"
  - trigger: "\"\"\t"
    replace: "¨"
  - trigger: "rr\t"
    replace: "⍴"
  - trigger: "pp\t"
    replace: "⍴"
  - trigger: "[:\t"
    replace: "⍠"
  - trigger: ":]\t"
    replace: "⍠"
  - trigger: "[=\t"
    replace: "⌸"
  - trigger: "=]\t"
    replace: "⌸"
  - trigger: "[<\t"
    replace: "⌺"
  - trigger: ">]\t"
    replace: "⌺"
  - trigger: "T_\t"
    replace: "⌶"
  - trigger: "II\t"
    replace: "⌶"